---
title: "3 Linear regression"
author: "Jishen Yin"
date: "2019/11/28"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab: Linear Regression

## Libraries

```{r, warning=FALSE}
library(MASS)
library(ISLR)
library(car)
```

## Simple Linear Regression

```{r}
data(Boston)
names(Boston)
```

```{r}
lm.fit <- lm(medv~lstat, data = Boston)
```

```{r}
lm.fit
summary(lm.fit)
```

```{r}
names(lm.fit)
coef(lm.fit)
```

```{r}
confint(lm.fit)
```

```{r}
predict(lm.fit, data.frame(lstat = c(5, 10, 15)),
        interval = "confidence")
predict(lm.fit, data.frame(lstat = c(5, 10, 15)),
        interval = "prediction")
```

```{r}
attach(Boston)
plot(lstat, medv, col = "red", pch = "+")
abline(lm.fit, lwd = 3)
```

```{r}
par(mfrow = c(2,2))
plot(lm.fit)
```

```{r}
plot(predict(lm.fit), residuals(lm.fit))
plot(predict(lm.fit), rstudent(lm.fit))
```

```{r}
plot(hatvalues(lm.fit))
which.max(hatvalues(lm.fit))
```

## Multiple Linear Regression

```{r}
lm.fit <- lm(medv~., data = Boston)
summary(lm.fit)
```

```{r}
vif(lm.fit)
```

```{r}
lm.fit1 <- lm(medv~.-age, data = Boston)
summary(lm.fit1)
```

## Interaction Terms

```{r}
summary(lm(medv~lstat+age, data = Boston))
```

## Non-linear Transformations of the Predictors

```{r}
lm.fit2 <- lm(medv~lstat+I(lstat^2), data = Boston)
summary(lm.fit2)
```

```{r}
lm.fit <- lm(medv~lstat, data = Boston)
anova(lm.fit, lm.fit2)
```

```{r}
par(mfrow = c(2,2))
plot(lm.fit2)
```

```{r}
lm.fit5 <- lm(medv~poly(lstat,5))
summary(lm.fit5)
```

```{r}
summary(lm(medv~log(rm), data = Boston))
```

## Qualitative Predictors

```{r}
data(Carseats)
names(Carseats)
```

```{r}
lm.fit <- lm(Sales~.+Income:Advertising+Price:Age, data = Carseats)
summary(lm.fit)
```

```{r}
attach(Carseats)
contrasts(ShelveLoc)
```