---
title: "4 Classification"
author: "Jishen Yin"
date: "2019/11/28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab: Logistic Regression, LDA, QDA and KNN

## The Stock Market Data

```{r}
library(ISLR)
names(Smarket)
dim(Smarket)
summary(Smarket)
pairs(Smarket)
```

```{r}
cor(Smarket[,-9])
```

```{r, warning=FALSE}
plot(Smarket$Volume)
```

## Logistic Regression

```{r}
glm.fits <- glm(Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume,
                data = Smarket, family = binomial)
summary(glm.fits)
```

```{r}
coef(glm.fits)
summary(glm.fits)$coef
summary(glm.fits)$coef[,4]
```

```{r}
glm.probs <- predict(glm.fits, type = "response")
glm.probs[1:10]
attach(Smarket)
contrasts(Direction)
```

```{r}
glm.pred <- rep("Down", 1250)
glm.pred[glm.probs>.5] <- "Up"
table(glm.pred, Direction)
mean(glm.pred == Direction)
```

```{r}
train <- (Year<2005)
Smarket.2005 <- Smarket[!train,]
dim(Smarket.2005)
Direction.2005 <- Direction[!train]
```

```{r}
glm.fits <- glm(Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume, subset = train,
                data = Smarket, family = binomial)
glm.probs <- predict(glm.fits, Smarket.2005, type = "response")
```

```{r}
glm.pred <- rep("Down", 252)
glm.pred[glm.probs>.5] <- "Up"
table(glm.pred, Direction.2005)
mean(glm.pred == Direction.2005)
```

```{r}
glm.fits <- glm(Direction~Lag1+Lag2, subset = train, data = Smarket,
                family = binomial)
glm.probs <- predict(glm.fits, Smarket.2005, type = "response")
glm.pred <- rep("Down", 252)
glm.pred[glm.probs>.5] <- "Up"
table(glm.pred, Direction.2005)
mean(glm.pred == Direction.2005)
```

```{r}
predict(glm.fits, newdata = data.frame(Lag1=c(1.2,1.5),
                                       Lag2=c(1,1.-0.8)), type = "response")
```

## Linear Discriminant Analysis

```{r}
library(MASS)
lda.fit <- lda(Direction~Lag1+Lag2, data = Smarket, subset = train)
lda.fit
```

```{r}
plot(lda.fit)
```

```{r}
lda.pred <- predict(lda.fit, Smarket.2005)
names(lda.pred)
```

```{r}
lda.class <- lda.pred$class
table(lda.class, Direction.2005)
mean(lda.class == Direction.2005)
```

```{r}
sum(lda.pred$posterior[,1]>=.5)
sum(lda.pred$posterior[,1]<.5)
```

```{r}
lda.pred$posterior[1:20,1]
lda.class[1:20]
```

```{r}
sum(lda.pred$posterior[,1]>.9)
```

## Quadratic Discriminant Analysis

```{r}
qda.fit <- qda(Direction~Lag1+Lag2, data = Smarket, subset = train)
qda.fit
```

```{r}
qda.class <- predict(qda.fit, Smarket.2005)$class
table(qda.class, Direction.2005)
mean(qda.class == Direction.2005)
```

## K-Nearest Neighbors

```{r}
library(class)
train.X <- cbind(Smarket$Lag1, Smarket$Lag2)[train,]
test.X <- cbind(Smarket$Lag1, Smarket$Lag2)[!train,]
train.Direction <- Direction[train]
```

```{r}
set.seed(1)
knn.pred <- knn(train.X, test.X, train.Direction, k = 1)
table(knn.pred, Direction.2005)
mean(knn.pred == Direction.2005)
```

```{r}
knn.pred <- knn(train.X, test.X, train.Direction, k = 3)
table(knn.pred, Direction.2005)
mean(knn.pred == Direction.2005)
```

## An Application to Caravan Insurance Data

```{r}
data(Caravan)
dim(Caravan)
attach(Caravan)
summary(Purchase)
```

```{r}
standardized.X <- scale(Caravan[,-86])
```

```{r}
test <- 1:1000
train.X <- standardized.X[-test,]
test.X <- standardized.X[test,]
train.Y <- Purchase[-test]
test.Y <- Purchase[test]
set.seed(1)
knn.pred <- knn(train.X, test.X, train.Y, k = 1)
table(knn.pred, test.Y)
mean(test.Y==knn.pred)
```

```{r}
knn.pred <- knn(train.X, test.X, train.Y, k = 3)
table(knn.pred, test.Y)
mean(test.Y==knn.pred)
knn.pred <- knn(train.X, test.X, train.Y, k = 5)
table(knn.pred, test.Y)
mean(test.Y==knn.pred)
```

```{r, warning=FALSE}
glm.fits <- glm(Purchase~., data = Caravan, family = binomial,
                subset = -test)
glm.probs <- predict(glm.fits, Caravan[test,], type = "response")
glm.pred <- rep("No", 1000)
glm.pred[glm.probs>.5] <- "Yes"
table(glm.pred, test.Y)
mean(glm.pred == test.Y)
```

