---
title: "7 Moving Beyond Linearity"
author: "Jishen Yin"
date: "2019/11/29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab: Non-Linear Modeling

```{r}
library(ISLR)
attach(Wage)
```

## Polynomial Regression and Step Functions

```{r}
fit <- lm(wage~poly(age,4), data = Wage)
coef(summary(fit))
```

```{r}
fit2 <- lm(wage~poly(age, 4, raw = TRUE), data = Wage)
coef(summary(fit2))
```

```{r}
fit2a <- lm(wage~age+I(age^2)+I(age^3)+I(age^4), data = Wage)
coef(fit2a)
```

```{r}
fit2b <- lm(wage~cbind(wage, wage^2, wage^3, wage^4), data = Wage)
```

```{r}
agelims <- range(age)
age.grid <- seq(from = agelims[1], to = agelims[2])
preds <- predict(fit, newdata = list(age = age.grid), se = TRUE)
se.bands <- cbind(preds$fit+2*preds$se.fit, preds$fit-2*preds$se.fit)
```

```{r}
plot(age, wage, xlim = agelims, cex = .5, col = "darkgrey")
title("Degree-4 Polynomial", outer = TRUE)
lines(age.grid, preds$fit, lwd = 2, col = "blue")
matlines(age.grid, se.bands, lwd = 1, col = "blue", lty = 3)
```

```{r}
preds2 <- predict(fit2, newdata = list(age = age.grid), se = TRUE)
max(abs(preds$fit-preds2$fit))
```

```{r}
fit.1 <- lm(wage~age, data = Wage)
fit.2 <- lm(wage~poly(age,2), data = Wage)
fit.3 <- lm(wage~poly(age,3), data = Wage)
fit.4 <- lm(wage~poly(age,4), data = Wage)
fit.5 <- lm(wage~poly(age,5), data = Wage)
anova(fit.1, fit.2, fit.3, fit.4, fit.5)
```

```{r}
coef(summary(fit.5))
```

```{r}
fit.1 <- lm(wage~education+age, data = Wage)
fit.2 <- lm(wage~education+poly(age,2), data = Wage)
fit.3 <- lm(wage~education+poly(age,3), data = Wage)
anova(fit.1, fit.2, fit.3)
```

```{r}
fit <- glm(I(wage>250)~poly(age, 4), data = Wage, family = binomial)
```

```{r}
preds <- predict(fit, newdata = list(age = age.grid), se = TRUE)
```

```{r}
pfit <- exp(preds$fit)/(1+exp(preds$fit))
se.bands.logit <- cbind(preds$fit+2*preds$se.fit, preds$fit-2*preds$se.fit)
se.bands <- exp(se.bands.logit)/(1+exp(se.bands.logit))
```

```{r}
preds <- predict(fit, newdata = list(age = age.grid), type = "response", se = TRUE)
```

```{r}
plot(age, I(wage>250), xlim = agelims, type = "n", ylim = c(0,.2))
points(jitter(age), I((wage>250)/5), cex = .5, pch = "|", col = "darkgrey")
lines(age.grid, pfit, lwd = 2, col = "blue")
matlines(age.grid, se.bands, lwd = 1, col = "blue", lty = 3)
```

```{r}
table(cut(age,4))
fit <- lm(wage~cut(age,4), data = Wage)
coef(summary(fit))
```

## Splines

```{r}
library(splines)
fit <- lm(wage~bs(age, knots = c(25, 40, 60)), data = Wage)
pred <- predict(fit, newdata = list(age = age.grid), se = TRUE)
plot(age, wage, col = "grey")
lines(age.grid, pred$fit, lwd = 2)
lines(age.grid, pred$fit + 2*pred$se, lty = "dashed")
lines(age.grid, pred$fit - 2*pred$se, lty = "dashed")
```

```{r}
dim(bs(age, knots = c(25,40,60)))
dim(bs(age, df = 6))
attr(bs(age, df = 6), "knots")
```

```{r}
fit2 <- lm(wage~ns(age, df = 4), data = Wage)
pred2 <- predict(fit2, newdata = list(age = age.grid), se = TRUE)
plot(age.grid, pred2$fit, col = "red", lwd = 2)
```

```{r, warning=FALSE}
plot(age, wage, xlim = agelims, cex = .5, col = "darkgrey")
title("Smoothing Spline")
fit <- smooth.spline(age, wage, df = 16)
fit2 <- smooth.spline(age, wage, cv = TRUE)
fit2$df
lines(fit, col = "red", lwd = 2)
lines(fit2, col = "blue", lwd = 2)
legend("topright", legend = c("16 DF", "6.8 DF"),
       col = c("red", "blue"), lty = 1, lwd = 2, cex = .8)
```

```{r}
plot(age, wage, xlim = agelims, cex = .5, col = "darkgrey")
title("Local Regression")
fit <- loess(wage~age, span = .2, data = Wage)
fit2 <- loess(wage~age, span = .5, data = Wage)
lines(age.grid, predict(fit, data.frame(age = age.grid)), col = "red", lwd = 2)
lines(age.grid, predict(fit2, data.frame(age = age.grid)), col = "blue", lwd = 2)
legend("topright", legend = c("Span=0.2", "Span=0.5"),
       col = c("red", "blue"), lty = 1, lwd = 2, cex = .8)
```
